// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} url
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DownloadExtension(url) {
    let $resultPromise = /** @type {any} */($Call.ByID(1955004975, url));
    return $resultPromise;
}

/**
 * @param {$models.DesktopApp} app
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ExecApp(app) {
    let $resultPromise = /** @type {any} */($Call.ByID(2980717694, app));
    return $resultPromise;
}

/**
 * @returns {Promise<{ [_: string]: $models.DesktopApp }> & { cancel(): void }}
 */
export function GetDesktopApps() {
    let $resultPromise = /** @type {any} */($Call.ByID(2455285118));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<number> & { cancel(): void }}
 */
export function GetProtoServerPort() {
    let $resultPromise = /** @type {any} */($Call.ByID(3908627508));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.DesktopApp.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
