// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sync$0 from "../../../../sync/models.js";

export class ClutchPkgJson {
    /**
     * Creates a new ClutchPkgJson instance.
     * @param {Partial<ClutchPkgJson>} [$$source = {}] - The source object to create the ClutchPkgJson.
     */
    constructor($$source = {}) {
        if (!("clutch" in $$source)) {
            /**
             * @member
             * @type {{"name": string, "repo": string, "description": string, "longDescription": string, "dev": {"distDir": string, "devUrl": string}}}
             */
            this["clutch"] = {"name": "", "repo": "", "description": "", "longDescription": "", "dev": {"distDir": "", "devUrl": ""}};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClutchPkgJson instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClutchPkgJson}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClutchPkgJson(/** @type {Partial<ClutchPkgJson>} */($$parsedSource));
    }
}

export class ClutchServices {
    /**
     * Creates a new ClutchServices instance.
     * @param {Partial<ClutchServices>} [$$source = {}] - The source object to create the ClutchServices.
     */
    constructor($$source = {}) {
        if (!("App" in $$source)) {
            /**
             * @member
             * @type {application$0.App | null}
             */
            this["App"] = null;
        }
        if (!("IsVisible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsVisible"] = false;
        }
        if (!("Services" in $$source)) {
            /**
             * @member
             * @type {application$0.Service[]}
             */
            this["Services"] = [];
        }
        if (!("UserConfigDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UserConfigDir"] = "";
        }
        if (!("UserHomeDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UserHomeDir"] = "";
        }
        if (!("ClutchDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ClutchDir"] = "";
        }
        if (!("ExtensionsDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ExtensionsDir"] = "";
        }
        if (!("RPCServerPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["RPCServerPort"] = 0;
        }
        if (!("Mu" in $$source)) {
            /**
             * @member
             * @type {sync$0.Mutex | null}
             */
            this["Mu"] = null;
        }
        if (!("ConfirmCh" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["ConfirmCh"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClutchServices instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClutchServices}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        const $$createField8_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("App" in $$parsedSource) {
            $$parsedSource["App"] = $$createField0_0($$parsedSource["App"]);
        }
        if ("Services" in $$parsedSource) {
            $$parsedSource["Services"] = $$createField2_0($$parsedSource["Services"]);
        }
        if ("Mu" in $$parsedSource) {
            $$parsedSource["Mu"] = $$createField8_0($$parsedSource["Mu"]);
        }
        return new ClutchServices(/** @type {Partial<ClutchServices>} */($$parsedSource));
    }
}

export class DesktopApp {
    /**
     * Creates a new DesktopApp instance.
     * @param {Partial<DesktopApp>} [$$source = {}] - The source object to create the DesktopApp.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("genericName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["genericName"] = "";
        }
        if (!("comment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("exec" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["exec"] = "";
        }
        if (!("terminal" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["terminal"] = false;
        }
        if (!("keywords" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["keywords"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopApp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DesktopApp}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keywords" in $$parsedSource) {
            $$parsedSource["keywords"] = $$createField7_0($$parsedSource["keywords"]);
        }
        return new DesktopApp(/** @type {Partial<DesktopApp>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = application$0.App.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = application$0.Service.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = sync$0.Mutex.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($Create.Any);
