version: '3'

includes:
  common: ./build/Taskfile.yml
  linux: ./build/linux/Taskfile.yml

vars:
  APP_NAME: "clutch"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    deps:
      - task: build:packages
      - task: common:build:frontend
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

  build:packages:
    cmds:
      - mkdir -p ./cmd/clutch/bundled
      - cd ./packages/api && pnpm run build && cp dist ../../cmd/clutch/bundled/api-dist -r
      - cd ./packages/ext-runtime && pnpm run build && cp dist ../../cmd/clutch/bundled/ext-runtime-dist -r
      - cp ./packages/ext-runtime/dist/cli.cjs ./internal/runtime/cli.cjs

