version: '3'

includes:
  common: ./build/Taskfile.yml
  linux: ./build/linux/Taskfile.yml

vars:
  APP_NAME: "clutch"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

tasks:
  build:api:
    summary: Builds the api package
    dir: ./packages/api
    cmds:
      - pnpm run build
      - cp ./dist ../../cmd/clutch/api-dist -r

  build:compat-layer:
    summary: Builds the compat-layer package
    dir: ./packages/compat-layer
    cmds:
      - pnpm run build
      - cp ./dist ../../cmd/clutch/compat-layer-dist -r

  build:ext-runtime:
    summary: Builds the runtime package
    dir: ./packages/ext-runtime
    cmds:
      - pnpm run build
      - cp ./dist ../../cmd/clutch/ext-runtime-dist -r

  build:packages:
    summary: Builds all the packages
    deps:
      - build:api
      - build:compat-layer
      - build:ext-runtime
  
  build:wails:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  dev:
    summary: Runs the application in development mode
    deps:
      - build:api
      - build:compat-layer
      - build:ext-runtime
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

  run:
    summary: Runs the application
    cmds:
      - '{{.BIN_DIR}}/{{.APP_NAME}} --dev'

  # package:
  #   summary: Packages a production build of the application
  #   cmds:
  #     - task: "{{OS}}:package"
  #

