// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "extension:error": { [_ in string]?: any };
            "extension:render": { [_ in string]?: any };
            "time": string;
        }
    }
}
