// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class Author {
    /**
     * Creates a new Author instance.
     * @param {Partial<Author>} [$$source = {}] - The source object to create the Author.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("handle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["handle"] = "";
        }
        if (!("avatar" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["avatar"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Author instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Author}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Author(/** @type {Partial<Author>} */($$parsedSource));
    }
}

export class Command {
    /**
     * Creates a new Command instance.
     * @param {Partial<Command>} [$$source = {}] - The source object to create the Command.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Command instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Command}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Command(/** @type {Partial<Command>} */($$parsedSource));
    }
}

export class Extension {
    /**
     * Creates a new Extension instance.
     * @param {Partial<Extension>} [$$source = {}] - The source object to create the Extension.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {Author}
             */
            this["author"] = (new Author());
        }
        if (!("download_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["download_count"] = 0;
        }
        if (!("categories" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["categories"] = [];
        }
        if (!("icons" in $$source)) {
            /**
             * @member
             * @type {Icons}
             */
            this["icons"] = (new Icons());
        }
        if (!("commands" in $$source)) {
            /**
             * @member
             * @type {Command[]}
             */
            this["commands"] = [];
        }
        if (!("download_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_url"] = "";
        }
        if (!("store_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["store_url"] = "";
        }
        if (!("source_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_url"] = "";
        }
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Extension instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Extension}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField4_0($$parsedSource["author"]);
        }
        if ("categories" in $$parsedSource) {
            $$parsedSource["categories"] = $$createField6_0($$parsedSource["categories"]);
        }
        if ("icons" in $$parsedSource) {
            $$parsedSource["icons"] = $$createField7_0($$parsedSource["icons"]);
        }
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField8_0($$parsedSource["commands"]);
        }
        return new Extension(/** @type {Partial<Extension>} */($$parsedSource));
    }
}

export class Icons {
    /**
     * Creates a new Icons instance.
     * @param {Partial<Icons>} [$$source = {}] - The source object to create the Icons.
     */
    constructor($$source = {}) {
        if (!("light" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["light"] = "";
        }
        if (!("dark" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dark"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Icons instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Icons}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Icons(/** @type {Partial<Icons>} */($$parsedSource));
    }
}

export class InstalledExt {
    /**
     * Creates a new InstalledExt instance.
     * @param {Partial<InstalledExt>} [$$source = {}] - The source object to create the InstalledExt.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("installed_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["installed_at"] = null;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("commands" in $$source)) {
            /**
             * @member
             * @type {Command[]}
             */
            this["commands"] = [];
        }
        if (!("icons" in $$source)) {
            /**
             * @member
             * @type {Icons}
             */
            this["icons"] = (new Icons());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstalledExt instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstalledExt}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField6_0($$parsedSource["commands"]);
        }
        if ("icons" in $$parsedSource) {
            $$parsedSource["icons"] = $$createField7_0($$parsedSource["icons"]);
        }
        return new InstalledExt(/** @type {Partial<InstalledExt>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Author.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = Icons.createFrom;
const $$createType3 = Command.createFrom;
const $$createType4 = $Create.Array($$createType3);
