// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} name
 * @returns {$CancellablePromise<$models.Command[]>}
 */
export function GetExtensionCommands(name) {
    return $Call.ByID(77650366, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Extension[]>}
 */
export function GetExtensions() {
    return $Call.ByID(1370714809).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.InstalledExt[]>}
 */
export function GetInstalledExtensions() {
    return $Call.ByID(2508679329).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function InstallExtension(id) {
    return $Call.ByID(1002632797, id);
}

/**
 * @param {string} query
 * @returns {$CancellablePromise<$models.Extension[]>}
 */
export function SearchExtensions(query) {
    return $Call.ByID(433956879, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function UninstallExtension(name) {
    return $Call.ByID(1062684694, name);
}

// Private type creation functions
const $$createType0 = $models.Command.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Extension.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.InstalledExt.createFrom;
const $$createType5 = $Create.Array($$createType4);
