import type { OpaqueHandle } from "react-reconciler";
import type { JSONNode, Container } from "./types";
type Parent = JSONNode | Container;
declare function appendChildToParent(parent: Parent, child: JSONNode | string): void;
declare function removeChildFromParent(parent: Parent, child: JSONNode | string): void;
export declare const hostConfig: {
    readonly supportsMutation: true;
    readonly supportsPersistence: false;
    readonly supportsHydration: false;
    readonly isPrimaryRenderer: true;
    readonly getPublicInstance: (instance: JSONNode | string) => JSONNode;
    readonly getRootHostContext: () => object;
    readonly getChildHostContext: () => object;
    readonly prepareForCommit: () => null;
    readonly resetAfterCommit: () => void;
    readonly createInstance: (type: string, props: Record<string, unknown>, _rootContainer: Container, _hostContext: object, internalInstanceHandle: OpaqueHandle) => JSONNode;
    readonly createTextInstance: (text: string, _rootContainer: Container, _hostContext: object, _internalInstanceHandle: OpaqueHandle) => string;
    readonly appendInitialChild: typeof appendChildToParent;
    readonly appendChild: typeof appendChildToParent;
    readonly appendChildToContainer: (container: Container, child: JSONNode | string) => void;
    readonly insertBefore: (parentInstance: JSONNode, child: JSONNode | string, beforeChild: JSONNode | string) => void;
    readonly insertInContainerBefore: (container: Container, child: JSONNode | string, beforeChild: JSONNode | string) => void;
    readonly removeChild: typeof removeChildFromParent;
    readonly removeChildFromContainer: typeof removeChildFromParent;
    readonly commitUpdate: (instance: JSONNode, _type: string, _oldProps: Record<string, unknown>, newProps: Record<string, unknown>) => void;
    readonly commitTextUpdate: (_textInstance: string, _oldText: string, _newText: string) => void;
    readonly finalizeInitialChildren: () => boolean;
    readonly shouldSetTextContent: () => boolean;
    readonly clearContainer: (container: Container) => void;
    readonly scheduleTimeout: typeof setTimeout;
    readonly cancelTimeout: (id: NodeJS.Timeout) => void;
    readonly noTimeout: -1;
    readonly getCurrentUpdatePriority: () => number;
    readonly setCurrentUpdatePriority: () => void;
    readonly resolveUpdatePriority: () => number;
    readonly resolveEventTimeStamp: () => number;
    readonly trackSchedulerEvent: () => void;
    readonly resolveEventType: () => string | null;
    readonly shouldAttemptEagerTransition: () => boolean;
    readonly maySuspendCommit: () => boolean;
    readonly preloadInstance: () => boolean;
    readonly startSuspendingCommit: () => void;
    readonly suspendInstance: () => void;
    readonly waitForCommitToBeReady: () => null;
    readonly preparePortalMount: () => void;
    readonly getInstanceFromNode: () => null;
    readonly beforeActiveInstanceBlur: () => void;
    readonly afterActiveInstanceBlur: () => void;
    readonly prepareScopeUpdate: () => void;
    readonly getInstanceFromScope: () => null;
    readonly detachDeletedInstance: () => void;
    readonly commitMount: () => void;
    readonly hideInstance: () => void;
    readonly hideTextInstance: () => void;
    readonly unhideInstance: () => void;
    readonly unhideTextInstance: () => void;
    readonly resetTextContent: () => void;
    readonly supportsMicrotasks: true;
    readonly scheduleMicrotask: typeof queueMicrotask;
    readonly resetFormInstance: () => void;
    readonly requestPostPaintCallback: () => void;
    readonly NotPendingTransition: null;
    readonly HostTransitionContext: {};
};
export default hostConfig;
//# sourceMappingURL=host-config.d.ts.map