// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as socket$0 from "../socket/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.Extension | null>}
 */
export function GetActiveExtension() {
    return $Call.ByID(3452178246).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<json$0.RawMessage>}
 */
export function GetLastRender() {
    return $Call.ByID(216706203);
}

/**
 * @returns {$CancellablePromise<socket$0.LifecycleManager | null>}
 */
export function GetLifecycle() {
    return $Call.ByID(1108324441).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {json$0.RawMessage} data
 * @returns {$CancellablePromise<void>}
 */
export function HandleRenderResponse(data) {
    return $Call.ByID(3129774772, data);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function NavigationPop() {
    return $Call.ByID(1013032950);
}

/**
 * @param {string} handlerID
 * @param {json$0.RawMessage} event
 * @returns {$CancellablePromise<void>}
 */
export function SendEvent(handlerID, event) {
    return $Call.ByID(3824779037, handlerID, event);
}

/**
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function SetOnError(fn) {
    return $Call.ByID(3894169464, fn);
}

/**
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function SetOnRender(fn) {
    return $Call.ByID(4000334018, fn);
}

/**
 * @param {socket$0.Server | null} srv
 * @returns {$CancellablePromise<void>}
 */
export function SetSocketServer(srv) {
    return $Call.ByID(3971781573, srv);
}

/**
 * @param {string} name
 * @param {string} command
 * @returns {$CancellablePromise<$models.Extension | null>}
 */
export function StartExtension(name, command) {
    return $Call.ByID(9105272, name, command).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopExtension() {
    return $Call.ByID(3888624778);
}

// Private type creation functions
const $$createType0 = $models.Extension.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = socket$0.LifecycleManager.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
