// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Hide() {
    return $Call.ByID(3886932885);
}

/**
 * @param {application$0.Window} w
 * @returns {$CancellablePromise<void>}
 */
export function SetWindow(w) {
    return $Call.ByID(3751224163, w);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Show() {
    return $Call.ByID(3554546212);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Toggle() {
    return $Call.ByID(2052252621);
}
