// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function EnsureInitialized() {
    return $Call.ByID(3865413572);
}

/**
 * @returns {$CancellablePromise<$models.App[]>}
 */
export function GetAll() {
    return $Call.ByID(827614907).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.IconIndex | null>}
 */
export function IconIndex() {
    return $Call.ByID(3334712067).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {$models.App} app
 * @returns {$CancellablePromise<void>}
 */
export function Launch(app) {
    return $Call.ByID(3356267879, app);
}

// Private type creation functions
const $$createType0 = $models.App.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.IconIndex.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
