// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class App {
    /**
     * Creates a new App instance.
     * @param {Partial<App>} [$$source = {}] - The source object to create the App.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("genericName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["genericName"] = "";
        }
        if (!("comment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("iconPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["iconPath"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("exec" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["exec"] = "";
        }
        if (!("execRaw" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["execRaw"] = "";
        }
        if (!("terminal" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["terminal"] = false;
        }
        if (!("keywords" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["keywords"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new App instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {App}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keywords" in $$parsedSource) {
            $$parsedSource["keywords"] = $$createField10_0($$parsedSource["keywords"]);
        }
        return new App(/** @type {Partial<App>} */($$parsedSource));
    }
}

export class IconIndex {
    /**
     * Creates a new IconIndex instance.
     * @param {Partial<IconIndex>} [$$source = {}] - The source object to create the IconIndex.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IconIndex instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IconIndex}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IconIndex(/** @type {Partial<IconIndex>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
